[project]
name = "django-react"
version = "0.1.0"
description = "A project integrating Django and React."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "django==5.1.7",
  "django-webpack-loader==3.1.1",
]
